#!/bin/bash
# Quick update script for new features

echo "🚀 Updating Sudoku Mastery with new features..."
echo ""
echo "✨ New Features & Fixes:"
echo "  - 🏆 Global Leaderboard System"
echo "  - 👤 Name Entry for Leaderboard"
echo "  - 🎮 Casual Mode Now Tracked on Leaderboard!"
echo "  - 📊 Top 10 Rankings per Mode & Difficulty"
echo "  - 🎯 Fixed Difficulty Selection (Casual & Challenge)"
echo "  - ⬅️ Change Difficulty Button During Gameplay"
echo "  - ⏱️ Complete Time Recording for ALL Modes"
echo "  - 🌏 Daily Puzzle with SGT Timezone (12AM reset)"
echo "  - 🎲 Date-based Seeding for Consistent Daily Puzzles"
echo "  - 🎯 All 5 Difficulties Available for Daily Puzzles"
echo "  - 🔐 Puzzle Security - Salt Protection (prevents cheating)"
echo "  - 🏷️ Seed Display in UI (transparency + debugging)"
echo "  - ✅ Better Loading States & Feedback"
echo ""

# Push to repository
echo "📤 Pushing to repository..."
git add .
git commit -m "Add leaderboard, name entry, all-difficulty dailies, puzzle security (salt), and seed display" || echo "Nothing to commit"
git push origin main

echo ""
echo "✅ Done! Now deploy on your server:"
echo ""
echo "🔒 IMPORTANT: Set PUZZLE_SALT first!"
echo ""
echo "  ssh sudoku@breezehost-jp"
echo "  cd ~/sudoku-game"
echo "  git pull"
echo ""
echo "  # Set PUZZLE_SALT (REQUIRED for security!)"
echo "  cd backend"
echo "  nano .env"
echo "  # Add: PUZZLE_SALT=\"\$(openssl rand -hex 32)\""
echo "  cd .."
echo ""
echo "  # Deploy"
echo "  sudo docker compose down"
echo "  sudo docker compose build --no-cache"
echo "  sudo docker compose up -d"
echo "  sudo docker exec -it sudoku-backend npx prisma migrate deploy"
echo "  sudo docker compose restart"
echo ""
echo "🌐 Then visit:"
echo "  - https://sudoku.kyros.party/casual (see puzzle seed displayed)"
echo "  - https://sudoku.kyros.party/daily (choose difficulty, see seed)"
echo "  - https://sudoku.kyros.party/leaderboard (see names on leaderboard)"
echo ""
echo "📝 Notes:"
echo "  - Database migration required for displayName feature"
echo "  - PUZZLE_SALT prevents cheating (required!)"
echo "  - Seeds now displayed in UI for transparency"

